### ISSUE TITLE
dont process `children`, `key`, etc?

### ISSUE THREAD

**Issue by cah-timhuddle** [kaiyote/use-web-component#3]
There's a few special props in react, like `children`. If someone were to write a wrapper component that contains this hook and a web-component tag (like in the tests), and that component were meant to have children, the wrapper would have to destructure that out of the props arg itself right now, since passing it to the hook would result in `componentTag.children = childrenPropFromReact`, which would absolutely not work.

Maybe we should explicitly filter those out of the "smart" logic, and just dump them to the `returnProps` object

**Comment by kaiyote** [comment]
This feels like a real edge case. Under normal circumstances, if you're writing a `Wrapper Component` using the hook you're probably better off using the HoC, which will correctly pass children through. If you're just using the hook directly, then you don't have to worry about children, since you wouldn't be passing them to the hook anyway.

I think its fine to force manual destructuring of `children` for the odd case of `Hook Wrapper Component with Children`.

`key` is also a special case that doesn't actually come through on props, and even if it did iirc `key` has to be `string | number`, so it'd get passed through anyway.
